name: gas_distribution_station_model
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: null
  fluent_ui: ^4.5.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_side_menu: ^0.3.2
  floor: any
  faker: any
  tuple: ^2.0.1
  file_picker: ^8.0.5
  dart_mappable: ^4.2.2
  equatable: ^2.0.5
  uuid: ^3.0.7
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  provider: ^6.1.2
  defer_pointer: ^0.0.2
  transparent_pointer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: ^2.0.0
  msix: ^3.14.2
  dart_mappable_builder: ^4.2.3
  mobx_codegen: ^2.6.1
msix_config:
  identity_name: abc
  display_name: GdsPipeline
  publisher_display_name: Morozov
  languages: en-us
flutter:
  assets:
    - assets/valve_image.png
    - assets/percentage_valve_image.png
    - assets/meter_image.png
    - assets/heater_image.png
    - assets/reducer_image.png
    - assets/filter_image.png
    - assets/adorizer_image.png
    - assets/GRS.png
  uses-material-design: true